# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Sigma_inv_update <- function(c, d, v_design_list, beta, gamma_long, Q, Sigma_inv_scale_inv, Sigma_inv_df) {
    .Call(`_hotspotRM_Sigma_inv_update`, c, d, v_design_list, beta, gamma_long, Q, Sigma_inv_scale_inv, Sigma_inv_df)
}

alpha_update <- function(x, sum_n, kappa, omega, beta, log_sum_exp, alpha_prior_cov_inv) {
    .Call(`_hotspotRM_alpha_update`, x, sum_n, kappa, omega, beta, log_sum_exp, alpha_prior_cov_inv)
}

beta_update <- function(x, R, c, sum_n, sum_R, kappa, omega, beta, alpha, Sigma_inv_old, rho_old, log_sum_exp, beta_prior_mean_mat, beta_prior_mean_vec) {
    .Call(`_hotspotRM_beta_update`, x, R, c, sum_n, sum_R, kappa, omega, beta, alpha, Sigma_inv_old, rho_old, log_sum_exp, beta_prior_mean_mat, beta_prior_mean_vec)
}

gamma_update <- function(v_design, c, p_v, beta, Sigma_inv_old, Q, gamma_prior_cov_inv) {
    .Call(`_hotspotRM_gamma_update`, v_design, c, p_v, beta, Sigma_inv_old, Q, gamma_prior_cov_inv)
}

hotspotRM <- function(mcmc_samples, z, n, m, v, R, metrop_sd_rho_trans, sigma2_gamma_prior = NULL, a_sigma2_prior = NULL, b_sigma2_prior = NULL, Sigma_inv_scale_prior = NULL, Sigma_inv_df_prior = NULL, beta_init = NULL, gamma_init = NULL, alpha_init = NULL, sigma2_init = NULL, Sigma_inv_init = NULL, rho_init = NULL) {
    .Call(`_hotspotRM_hotspotRM`, mcmc_samples, z, n, m, v, R, metrop_sd_rho_trans, sigma2_gamma_prior, a_sigma2_prior, b_sigma2_prior, Sigma_inv_scale_prior, Sigma_inv_df_prior, beta_init, gamma_init, alpha_init, sigma2_init, Sigma_inv_init, rho_init)
}

omega_update <- function(x, m, beta, alpha, log_sum_exp) {
    .Call(`_hotspotRM_omega_update`, x, m, beta, alpha, log_sum_exp)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_hotspotRM_rcpp_pgdraw`, b, c)
}

rho_update <- function(c, d, R, beta, Sigma_inv, rho_old, Q, log_deter, beta_prior_mean_mat, metrop_sd_rho_trans, acctot_rho_trans) {
    .Call(`_hotspotRM_rho_update`, c, d, R, beta, Sigma_inv, rho_old, Q, log_deter, beta_prior_mean_mat, metrop_sd_rho_trans, acctot_rho_trans)
}

sigma2_update <- function(k, counter, n, d, alpha, shape_update, b_sigma2) {
    .Call(`_hotspotRM_sigma2_update`, k, counter, n, d, alpha, shape_update, b_sigma2)
}

