# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MLDM1 <- function(mcmc_samples, z, n, m, v, R, x, metrop_sd_rho_trans, sigma2_gamma_prior = NULL, Sigma_inv_scale_prior = NULL, Sigma_inv_df_prior = NULL, theta_init = NULL, gamma_init = NULL, Sigma_inv_init = NULL, rho_init = NULL) {
    .Call(`_MLDM_MLDM1`, mcmc_samples, z, n, m, v, R, x, metrop_sd_rho_trans, sigma2_gamma_prior, Sigma_inv_scale_prior, Sigma_inv_df_prior, theta_init, gamma_init, Sigma_inv_init, rho_init)
}

MLDM <- function(mcmc_samples, z, n, m, v, R, x, metrop_sd_rho_trans, sigma2_gamma_prior = NULL, a_sigma2_prior = NULL, b_sigma2_prior = NULL, Sigma_inv_scale_prior = NULL, Sigma_inv_df_prior = NULL, theta_init = NULL, gamma_init = NULL, alpha_init = NULL, sigma2_init = NULL, Sigma_inv_init = NULL, rho_init = NULL) {
    .Call(`_MLDM_MLDM`, mcmc_samples, z, n, m, v, R, x, metrop_sd_rho_trans, sigma2_gamma_prior, a_sigma2_prior, b_sigma2_prior, Sigma_inv_scale_prior, Sigma_inv_df_prior, theta_init, gamma_init, alpha_init, sigma2_init, Sigma_inv_init, rho_init)
}

Sigma_inv_update <- function(c, d, p_g, v_design_list, theta, gamma_long, Q, Sigma_inv_scale_inv, Sigma_inv_df) {
    .Call(`_MLDM_Sigma_inv_update`, c, d, p_g, v_design_list, theta, gamma_long, Q, Sigma_inv_scale_inv, Sigma_inv_df)
}

alpha_update <- function(X_star, sum_n, kappa, omega, theta, log_sum_exp, alpha_prior_cov_inv) {
    .Call(`_MLDM_alpha_update`, X_star, sum_n, kappa, omega, theta, log_sum_exp, alpha_prior_cov_inv)
}

gamma_update <- function(v_design_list, c, d, p_v, p_g, theta, Sigma_inv_old, Q, gamma_prior_cov_inv) {
    .Call(`_MLDM_gamma_update`, v_design_list, c, d, p_v, p_g, theta, Sigma_inv_old, Q, gamma_prior_cov_inv)
}

omega_update <- function(X_star, m, theta, alpha, log_sum_exp) {
    .Call(`_MLDM_omega_update`, X_star, m, theta, alpha, log_sum_exp)
}

p_signal_full_create <- function(beta, gamma, v) {
    .Call(`_MLDM_p_signal_full_create`, beta, gamma, v)
}

p_signal_space_create <- function(beta) {
    .Call(`_MLDM_p_signal_space_create`, beta)
}

psi1_create <- function(p_signal) {
    .Call(`_MLDM_psi1_create`, p_signal)
}

psi2_create <- function(p_signal) {
    .Call(`_MLDM_psi2_create`, p_signal)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_MLDM_rcpp_pgdraw`, b, c)
}

rho_update <- function(c, d, p_g, R, theta, Sigma_inv, rho_old, Q, log_deter, theta_prior_mean_mat, metrop_sd_rho_trans, acctot_rho_trans) {
    .Call(`_MLDM_rho_update`, c, d, p_g, R, theta, Sigma_inv, rho_old, Q, log_deter, theta_prior_mean_mat, metrop_sd_rho_trans, acctot_rho_trans)
}

sigma2_update <- function(k, counter, n, d, alpha, shape_update, b_sigma2) {
    .Call(`_MLDM_sigma2_update`, k, counter, n, d, alpha, shape_update, b_sigma2)
}

theta_update <- function(X_star, R, c, p_g, n, sum_R, kappa, omega, theta, alpha, Sigma_inv_old, rho_old, log_sum_exp, theta_prior_mean_mat, theta_prior_mean_vec) {
    .Call(`_MLDM_theta_update`, X_star, R, c, p_g, n, sum_R, kappa, omega, theta, alpha, Sigma_inv_old, rho_old, log_sum_exp, theta_prior_mean_mat, theta_prior_mean_vec)
}

